### ISSUE TITLE
Android crash app when build release v6.1.7

### ISSUE THREAD

**Issue by tuantvk** [Pushwoosh/pushwoosh-react-native-plugin#128]
i use `react-native: 0.60.4` and `pushwoosh-react-native-plugin: 6.1.7` app crash when open.
- android sdk version 30
- adb log
```
2021-10-11 13:41:57.553 4784-4784/? I/cs.npvdealerde: Late-enabling -Xcheck:jni
2021-10-11 13:41:57.599 4784-4784/? E/cs.npvdealerde: Unknown bits set in runtime_flags: 0x8000
2021-10-11 13:41:57.600 4784-4784/? W/cs.npvdealerde: Unexpected CPU variant for X86 using defaults: x86
2021-10-11 13:41:57.880 4784-4784/com.xxxxx I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2021-10-11 13:41:57.919 4784-4784/com.xxxxx I/FirebaseInitProvider: FirebaseApp initialization successful
2021-10-11 13:41:57.923 4784-4784/com.xxxxx E/Pushwoosh: This is not an Amazon device. The service is not available.
2021-10-11 13:41:57.924 4784-4784/com.xxxxx E/Pushwoosh: [HuaweiUtils] Huawei HMS Core SDK - Push Kit not integrated. Follow the guide to integrate the library to your project https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/android-integrating-sdk-0000001050040084-V5
2021-10-11 13:41:57.924 4784-4784/com.xxxxx E/Pushwoosh: This is not a Huawei device. The service is not available.
2021-10-11 13:41:57.929 4784-4823/com.xxxxx D/Pushwoosh: [CrashAnalytics] Looking for exceptions in: /data/user/0/com.xxxxx/files
2021-10-11 13:41:57.953 4784-4784/com.xxxxx E/Pushwoosh: Exception occurred
    java.lang.ClassNotFoundException: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.pushwoosh.w.r(Unknown Source:39)
        at com.pushwoosh.w.<init>(Unknown Source:141)
        at com.pushwoosh.r.c(Unknown Source:44)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension" on path: DexPathList[[zip file "/data/app/com.xxxxx-E_7ThcwTLX4scyDPLbHRiQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxxx-E_7ThcwTLX4scyDPLbHRiQ==/lib/x86, /data/app/com.xxxxx-E_7ThcwTLX4scyDPLbHRiQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.pushwoosh.w.r(Unknown Source:39) 
        at com.pushwoosh.w.<init>(Unknown Source:141) 
        at com.pushwoosh.r.c(Unknown Source:44) 
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-10-11 13:41:57.953 4784-4784/com.xxxxx D/AndroidRuntime: Shutting down VM
2021-10-11 13:41:57.955 4784-4784/com.xxxxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxx, PID: 4784
    java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at com.pushwoosh.w.r(Unknown Source:100)
        at com.pushwoosh.w.<init>(Unknown Source:141)
        at com.pushwoosh.r.c(Unknown Source:44)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-10-11 13:41:57.956 4784-4828/com.xxxxx D/NetworkSecurityConfig: No Network Security Config specified, using platform default
```

**Comment by wfhm** [comment]
@tuantvk 

I could not reproduce it so far. However, it looks like, for some reason, plugin sources are obfuscated. Could you please share your build.gradle files?
