### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by macojaune** [Pushwoosh/pushwoosh-react-native-plugin#57]
Working fine in debug mode, crashing when apk build for production realease. 
Here's the error log: 

```
2019-04-15 15:13:15.914 5415-5415/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mob.franceantilles.gp, PID: 5415
    java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at android.app.ActivityThread.installProvider(ActivityThread.java:6590)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at com.pushwoosh.f.a(Unknown Source:100)
        at com.pushwoosh.f.<init>(Unknown Source:127)
        at com.pushwoosh.t.a(Unknown Source:42)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2000)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1975)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6585)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-04-15 15:22:31.124 7041-7041/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mob.franceantilles.gp, PID: 7041
    java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at android.app.ActivityThread.installProvider(ActivityThread.java:6590)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Could not find class for name: com.pushwoosh.reactnativeplugin.PushwooshNotificationServiceExtension
        at com.pushwoosh.f.a(Unknown Source:100)
        at com.pushwoosh.f.<init>(Unknown Source:127)
        at com.pushwoosh.t.a(Unknown Source:42)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2000)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1975)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6585)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-04-15 15:22:31.125 564-564/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=7041 uid=10216 scontext=u:r:untrusted_app:s0:c216,c256,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
2019-04-15 15:22:31.126 564-564/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=7041 uid=10216 scontext=u:r:untrusted_app:s0:c216,c256,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
```

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by macojaune** [comment]
Hi @wfhm, any news ?

**Comment by wfhm** [comment]
@macojaune 

Do you use proguard when building in release mode? If so, could you please [add pushwoosh classes to a list of exceptions](https://www.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk-5.0#using-proguard)?

```
-keep class com.pushwoosh.** { *; }
-dontwarn com.pushwoosh.**
```

**Comment by macojaune** [comment]
Thank you very much it's working now 
(didn't know about proguard)
