### ISSUE TITLE
Android - Crash when push is received

### ISSUE THREAD

**Issue by ToniDB** [Pushwoosh/pushwoosh-react-native-plugin#66]
Hello there!
Every time that I receive a push notification, my app crashes.
This is my stack trace when it happens:

`2019-06-21 13:09:52.270 14130-14130/com.its4appslight E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.its4appslight, PID: 14130
    java.lang.RuntimeException: Unable to instantiate service com.pushwoosh.PushFcmIntentService: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushFcmIntentService" on path: DexPathList[[zip file "/data/app/com.its4appslight-2/base.apk"],nativeLibraryDirectories=[/data/app/com.its4appslight-2/lib/arm64, /data/app/com.its4appslight-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3449)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushFcmIntentService" on path: DexPathList[[zip file "/data/app/com.its4appslight-2/base.apk"],nativeLibraryDirectories=[/data/app/com.its4appslight-2/lib/arm64, /data/app/com.its4appslight-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3446)
        at android.app.ActivityThread.-wrap6(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        		... 10 more
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 13 more
     Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.its4appslight-2/base.apk:classes2.dex)
        		... 13 more`

**Comment by wfhm** [comment]
Hello @ToniDB,

Checking it!

**Comment by tuantvk** [comment]
You try update lib **pushwoosh-react-native-plugin** to version **5.15.2** or change firebase-core and firebase-messaging in file _**node_modules/pushwoosh-react-native-plugin/src/android/build.gradle**_

implementation "com.google.firebase:firebase-core**:(+,17.0.0)**"
implementation "com.google.firebase:firebase-messaging:**(+,19.0.0)**"

**Comment by wfhm** [comment]
@ToniDB

I could not reproduce the issue with the latest (5.15.2) version of the plugin, therefore may I ask you which one did you use in your app?

If it was not the latest one, the @tuantvk's answer might possibly address your issue - did you already try upgrading the plugin?

**Comment by ToniDB** [comment]
Yes @tuantvk answer worked for me. I downgrade the version and it started working again.
To upgrade the plugin to the latest version do I have to update all my android and react-native ecosystem? This is related to AndroidX migration, am I right?

Current using this config:
react-native: "0.59.8"

compileSdkVersion = 28
minSdkVersion = 16
buildToolsVersion = 28.0.3
targetSdkVersion = 27
supportLibVersion = 28.0.0

**Comment by wfhm** [comment]
@ToniDB,

It worked just fine with the following config:


    react-native-cli: 2.0.1
    react-native: 0.59.9

    buildToolsVersion = "28.0.3"
    minSdkVersion = 16
    compileSdkVersion = 28
    targetSdkVersion = 27
    supportLibVersion = "28.0.0"

Downgrading react-native version to 0.59.8 should not break anything, however please let us know if there will be any issues with it.
